### PR TITLE
Feats: extract additional beam/joints data for results csv export

### LINKED ISSUE #141: DFPreview is laggy and beams' axis off
The preview of the assembly is very laggy when activated. This might linked to how the preview is overwritten in the python component.
Also we need to find a better and more robust way to draw axis because some are off since based on the OBB of the element. We need something less computationally expensive for the visualization.

image

### PR DESCRIPTION
**Pull request by 9and3**
## Description
This is a PR to integrate some useful (at least for me) features during the AC evaluation. Mainly it's about extracting extra info from the beam and joints' geometries and exporting it in the CSV/.diffCheck. Basically all the extraction of the geometric features is done in the `df_geometries.py` module and the export is a plug-in in the csv row preparation function:

https://github.com/diffCheckOrg/diffCheck/blob/a7583ce96eb1d02932e0a90a394cf4e223fbf096/src/gh/components/DF_csv_exporter/code.py#L110-L127

> [!IMPORTANT]
> @DamienGilliard this is not tested for round woods. I believe that everything should work with basic cylinders.

## New features
- [x] **`DFBeam.compute_axis()`**: integrated a function that properly extract the axis from the beam. It takes the two farthest joints' centroids and build the vector axis from it (https://github.com/diffCheckOrg/diffCheck/pull/143/commits/a888e99ea6ed9999bcd4d79a6cf7952b1a55551d)
- [x] **extract/export beam length**: get the length of the above beam axis (`DFBeam.length`) and export it through the CSV. (https://github.com/diffCheckOrg/diffCheck/pull/143/commits/8b047e6845a2fb79e0fa5827aa008b9ce6ed9bca)
- [x] **extract/export relative position of joinst from beam's center**: this is some data I need to assess if there is really a deformation in my AR mapping. Feat design: Each joint's centroid is project to the beam's axis >> measure projection to center distance (signed) >> export on csv (https://github.com/diffCheckOrg/diffCheck/pull/143/commits/8b047e6845a2fb79e0fa5827aa008b9ce6ed9bca)
- [x] **extract/export jointface angles**: this is calculated between the normal of the joint face and the beam's axis. Feat design: detect face norma >> bring the axis and normal to the same direction >> calculate angles >> export (https://github.com/diffCheckOrg/diffCheck/pull/143/commits/8b047e6845a2fb79e0fa5827aa008b9ce6ed9bca)

## Changes
- [x] new output for the component  `DFExportResults` of the generated path for better debugging (https://github.com/diffCheckOrg/diffCheck/pull/143/commits/b34ac881c9df66e2324a646466c8998c8a313b06)

## Fixes
- [x] fix #141 : if the axis is now embedded in the dfbeam I hope to simply use it in the preview to avoid computation of the axis during the rendering (as it was) (https://github.com/diffCheckOrg/diffCheck/pull/143/commits/1dc468abbb6f80d7c5246f0d66a8e4d4eade6160)

### CODE REVIEW

**Comment by 9and3** [comment]
rfr @DamienGilliard / @eleniv3d in case you have a moment free.

**Comment by DamienGilliard** [comment]
I'll take a look tomorrow !

**Review by DamienGilliard — APPROVED** [review]
Went through it, nothing to report 👍
df_geometries really starts to be quite rich, certainly with the "state" logic.
Thanks !

**Comment by 9and3** [comment]
> Went through it, nothing to report 👍 df_geometries really starts to be quite rich, certainly with the "state" logic. Thanks !

And tedious if you ask.. Now everytime  you add a variable you need to serialize it with this state thing. But for now it is  what it is.

Thanks for the review!

**Pull request merged**
