### PR TITLE
test suite complement to pc and meshes + segmentation and registration

### PR DESCRIPTION
**Pull request by DamienGilliard**
This PR contains complements to the python test suite.  

It covers DFPointCloud (where a few methods were not tested) and DFMesh that was left "To Do"

It also concerns tests for the segmentation and registration bindings, done with:

3 tests for the registration part : 
- pure translation with 2 spheres
- pure rotation with two standford bunnies
- composite with standford bunnies

2 tests for segmentation: 
- 2 adjacent segments
- 2 distant segments

The main files changed is pybind_test_unit.py , and 3 ply files were added

additionally, 
- the name for the GetAxisAlignedBoundingBox() (new name) was not consistent with the other naming schemas and was adapted.
- The apply_transformation method was also missing from the pybind and was added.

### CODE REVIEW

**Comment by 9and3** [comment]
took the liberty to convert it to draft, when ready you can convert it again.

**Comment by DamienGilliard** [comment]
one day my PRs will have the right tags, assignees and links from the get go, I promise

**Comment by DamienGilliard** [comment]
Note: the segmentation test proved not to be 100% stable, but now it was tested around 10 times locally and worked every time. Should work every time

**Comment by 9and3** [comment]
> Note: the segmentation test proved not to be 100% stable, but now it was tested around 10 times locally and worked every time. Should work every time

I have contrasting feelings :) Where is it that you think is failing? Why it is proved not to be 100%? Ideally they should always pass and be sure, that's the goal. If you think your asserts are too tight please add thresholds (e.g. round up one decimal in floats checks). Where is in the tests that this is failing "sometimes"?

**Comment by 9and3** [comment]
> Small change compared to description: the rotation test is done with the bunny as well, for convenience.

can "edit" the description directly

**Comment by DamienGilliard** [comment]
> > Note: the segmentation test proved not to be 100% stable, but now it was tested around 10 times locally and worked every time. Should work every time
> 
> this comment unleashed in me contrasting feelings :) Where is it that you think is failing? Why it is proved not to be 100%? Ideally they should always pass and be sure, that's the goal. If you think your asserts are too tight please add thresholds (e.g. round up one decimal in floats checks). Where is in the tests that this is failing "sometimes"?

Sorry the sentence was not clear, I meant that with previous parameters, the segmentation returned most of the time 2 segments (as it should) but sometimes 3 segments. Now the parameters have been adapted and have worked every time until now.

**Comment by DamienGilliard** [comment]
python part of issue #62 solved here

**Comment by DamienGilliard** [comment]
@9and3  I believe this PR is ready for review.  The PR description has been updated and explains the changes done. Thanks for your help in structuring my PR (even if it is still far from perfect ;) )

**Review by 9and3 — APPROVED** [review]
thanks for the PR! My feedback:

- concerning the refactoring of the `GetBB`, for me was not necessarly needed since `Get` was only kept for the *getters* in the class but we can leave it like this, it's a minor detail.
- nice for the transform method!

**Pull request merged**
