### PR TITLE
Rhino2DFChecker Exporter

### PR DESCRIPTION
**Pull request by 9and3**
This branch is for the development of an exporter of polysurfaces towards our backend c++ of DiffCheck. The Rhino/Gh will export a XML file and the backend will parse it into memory. The PR will include:

- [ ] a basic project for the ghpy diffcheck
- [ ] a component for the exporter towards xml
- [ ] the parser from the backend side

This is a first idea on how to implement the exporter. To note that later, when we will have a python wrapper this won't be different (we will still parse polysurfaces into a nested list of 3 coordinates).

exporterRHDF

### CODE REVIEW

**Comment by 9and3** [comment]
Small update: on [dbe7d49](https://github.com/diffCheckOrg/diffCheck/pull/8/commits/dbe7d491ca55e4284876066f4e7a99cc0a60a483) there is a functioning version of the exporter. You can add it as a `.ghuser` object in the canvas. The export `.xml` has changed a bit but not much from the initial scheme.

Could you @eleniv3d give it a go and tell me if there are problems in the export?

[Download the user object](https://github.com/diffCheckOrg/diffCheck/actions/runs/8661759335/artifacts/1408538707)

gh_snap

I also added a basic CI to build the ghuser objects but I would like to close and merge this PR and open another one to design a proper pipeline for the gh python development framework (test, debug, release, etc).

**Comment by eleniv3d** [comment]
IMG_3962

This happens on windows 8 :)

**Comment by 9and3** [comment]
Thanks @eleniv3d ! Can you try it now? I updated the [PyPi](https://pypi.org/project/diffCheck/).
It shoudl update the module automatically but if not maybe try to close and reopen gh? I will also trying some local tests on another machine.

**Comment by 9and3** [comment]
Hello @eleniv3d ! 

Here's a new version you can [download here](https://github.com/diffCheckOrg/diffCheck/actions/runs/8686581799/artifacts/1413726487). You will have to deletee the old ghuser before dropping this new into your canvas.

I tested it in two machines and it should work. Let me know how it goes and if there other errors!

**Comment by eleniv3d** [comment]
1. Error running script (PythonException): name 'math' is not defined on Rhino 8.6.24101.5001

**Comment by 9and3** [comment]
Have you tried to close rhino and reopen everything?

**Comment by 9and3** [comment]
How about now with this one [here](https://github.com/diffCheckOrg/diffCheck/actions/runs/8688521276/artifacts/1414147498)?

I have no idea why the `import math` works on my two machines but not yours, in any case, I specified it.

Keep them coming @eleniv3d if there any other 🐛

**Comment by eleniv3d** [comment]
🐛🐛🐛
1. Error running script (PythonException): 'NoneType' object is not iterable

**Comment by 9and3** [comment]
> 🐛🐛🐛
> 
>     1. Error running script (PythonException): 'NoneType' object is not iterable. always post restarting rhino ;)

Can you double click the component and run it from the script editor play button and copy-past the full error appearing in the terminal plis? thanks!

**Comment by eleniv3d** [comment]
Hopefully this clear things up more

https://github.com/diffCheckOrg/diffCheck/assets/43600924/b27b7760-b97f-4d20-8188-c2c5d4534a19

**Comment by eleniv3d** [comment]
With btn since you prefer ;)

[DiffcheckExportTest.zip](https://github.com/diffCheckOrg/diffCheck/files/14979750/DiffcheckExportTest.zip)

**Comment by 9and3** [comment]
> With btn since you prefer ;)
> 
> [DiffcheckExportTest.zip](https://github.com/diffCheckOrg/diffCheck/files/14979750/DiffcheckExportTest.zip)

thanks! Thanks for the button, I am naively hoping that is the problem (which is not of course :) )

**Comment by 9and3** [comment]
Ok, the problem is in the brep. By looking at these isocurves I suspect that it can't be digested by our [joint detector](https://github.com/diffCheckOrg/diffCheck/blob/RhDFExporter/src/gh/diffCheck/diffCheck/df_joint_detector.py).

image

If I feed other breps it works fine.

@eleniv3d  could you point me to other polysurfaces from the dataset so that I can test which are causing problems please?

**Comment by eleniv3d** [comment]
@9and3 i confirm that it works on my computer for the other breps of our dataset that don't have this joint :) Attached also the .ghx and the exported .XML file in case you want to take a look

[Assembly_Test.zip](https://github.com/diffCheckOrg/diffCheck/files/14982399/Assembly_Test.zip)

test_export

**Comment by 9and3** [comment]
Hello @eleniv3d ,

I added a small repairer for these kind of degenerated surfaces:

image

I also add a detector to catch if the brep has holes, for now it's just a limitation and it would require an extra round of development. I marked it as an issue #11 .

I am closing now the PR for the exporter.

**Pull request merged**
