### PR TITLE
test for AddPoints() in DFPointCloud

### PR DESCRIPTION
**Pull request by DamienGilliard**
Tiny PR to add a test of AddPoints() method of DFPointCloud

The two files changed are 
- the DFPointCloudTest.cc for the c++ test of the AddPoints() method
- the test_pybind_units.py for its pybind

### CODE REVIEW

**Comment by DamienGilliard** [comment]
@9and3 I believe this PR is ready for review

**Review by 9and3 — CHANGES_REQUESTED** [review]
Lookin good the c++ test but we are missing the python one. Can you add it plis?

**Comment by 9and3** [comment]
I see.. Can you please close both of them and do an uniqu PR? Thanks!

**Comment by DamienGilliard** [comment]
@9and3 If you agree I'll close this one and integrate it into the other one. I'll do that this evening

**Comment by DamienGilliard** [comment]
@9and3 Here is the PR concerning only the AddPoints() method.

Sorry for the messiness with which I handled the various parallel PR...

**Review by 9and3 — APPROVED** [review]
lgtm! 🪨

**Pull request merged**
